### ISSUE TITLE
Bug in indentation of else: and elif in python

### ISSUE THREAD

**Issue by jontaa** [kbrose/vsc-python-indent#35] opened 2019-07-22 06:51 UTC
This is an remaining issue after the fix in https://github.com/kbrose/vsc-python-indent/issues/19

Here is how it works:
```
while True:
    result = i / 3
    if something:
        output = "Hello"
        elif something:
```

When I press enter at the last line above, the elif will be moved correctly to be on the same level as the if. No issues here.
This is how it looks after enter

```
while True:
    result = i / 3
    if something:
        output = "Hello"
    elif something:
```

But now lets say that I wanted to edit the elif somewhat, so I do this:
```
while True:
    result = i / 3
    if something:
        output = "Hello"
    elif some
```

And I then edit it to:
```
while True:
    result = i / 3
    if something:
        output = "Hello"
    elif somethingelse:
```
I press enter at the last line above, and get this:
```
while True:
    result = i / 3
    if something:
        output = "Hello"
elif somethingelse:
```

I think that the solution is to only indent it once, and not on subsequent edits of the line.
The above is an example with elif, but the same goes for else:

**Environment (please complete the following information):**
 - OS: OSX Mojave
 - Version of `Python Indent` 1.1.0
 - Version of Visual Studio Code: 1.35.0

**Comment by jontaa** [comment] 2019-07-22 08:11
This also triggers if the coder puts the else: or elif: on the correct indentation by old habit, and then presses enter, as it would also indent it a second time to the left, thus being incorrect.

**Comment by kbrose** [comment] 2019-07-24 02:05
Duplicate of #31 

Side note, you can make your code have syntax highlighting by putting the name of the language on the first line with the triple backtrack.

Like this:

    ```python
    def f(x):
        return True
    ```

results in nicely colored code:

```python
def f(x):
    return True
```

This makes it a lot easier to read, at least for me.

**Closed by kbrose** 2019-07-24 02:05 UTC
