### ISSUE TITLE
wrong indent when use "elif"

### ISSUE THREAD

**Issue by trotsky1997** [kbrose/vsc-python-indent#32] opened 2019-07-09 09:34 UTC
```
def foo():
    if 1:
        pass
    elif 0:#click "enter"
```
after click "enter",it comes to
```
def foo():
    if 1:
        pass
elif 0:
    |#new line
```

**Comment by trotsky1997** [comment] 2019-07-09 09:44
My suggestion for this problem
Some people like to redent before type "elif/else/except",but others don't.
You can add an setting called "preferation" or other name to let people control that funtion by theri own wish.

**Comment by trotsky1997** [comment] 2019-07-09 10:02
```
function dedentCurrentLine(line, tabSize) {
    const dedentKeywords = ["elif", "else", "except", "finally"];
    const trimmed = line.trim();
    if (trimmed.endsWith(":") && line.startsWith("        ")) { //little trick to fix that!
        if (dedentKeywords.some((keyword) => trimmed.startsWith(keyword))) {
            return Math.min(tabSize, indentationLevel(line));
        }
    }
    return 0;
}
exports.dedentCurrentLine = dedentCurrentLine;
//# sourceMappingURL=indent.js.map
```

**Comment by WhistleWhileYouWork** [comment] 2019-07-09 13:55
Duplicate of #31

I've updated the title of my issue to be more descriptive.

**Comment by kbrose** [comment] 2019-07-13 16:44
Agreed, seems to be a duplicate.

**Closed by kbrose** 2019-07-13 16:44 UTC
Labels: duplicate
